### ISSUE TITLE
OTIS Crash Data?

### ISSUE THREAD

**Issue by kettle11** [azavea/opendataphilly-jkan#108]
On the [Fatal Crashes](https://opendataphilly.org/datasets/fatal-crashes/) dataset it says this:

> For those conducting analysis, this dataset by PPD and [OTIS’ crash data](https://www.opendataphilly.org/datasets/vehicular-crash-data) should not be compared, or should be used together cautiously.

However that link to OTIS crash data no longer works. Is that dataset no longer available? The only other dataset I see that covers all crashes (not just fatal crashes) is this one: https://opendataphilly.org/datasets/vehicular-crashes/. However that appears to end in 2020.

Which dataset is the most comprehensive and up to date crash data set?

**Comment by Kistine** [comment]
Hi @kettle11 - I submitted a PR to update that link to the OTIS data entry - you are right that it was meant to connect to the /vehicular-crashes dataset. OTIS also recently published the latest data, so I submitted a pull request for that as well. In the interim, you can find those download links on the metadata for this dataset here: https://metadata.phila.gov/#home/datasetdetails/5543865420583086178c4eba/representationdetails/64f22d9087c9db002570f98a/

**Comment by kettle11** [comment]
@Kistine Thank you for the prompt and helpful response! It's much appreciated.

**Comment by BryanQuigley** [comment]
Fix is live, thanks for reporting the issue! Thanks Kistine for fixing it so fast!
