### ISSUE TITLE
Homepage, Suggested feature: search box 

### ISSUE THREAD

**Issue by BryanQuigley** [azavea/opendataphilly-jkan#13]
Likely worth waiting for #10, contribute upstream

Suggested feature: Add a search box to the homepage to match old OpenDataPhilly site. On submit, forward to Datasets page and populate search there.

**Comment by philippschmitt** [comment]
Suggested design: 
![image](https://user-images.githubusercontent.com/940395/225746663-c29d3894-fb58-4476-ab2c-a609f55bc99d.png)
