### ISSUE TITLE
Homepage, Suggested Feature Custom header image

### ISSUE THREAD

**Issue by BryanQuigley** [azavea/opendataphilly-jkan#14]
Likely worth waiting for #10, contribute upstream

Suggested feature: Add the ability to include a custom header image (See Bootstrap example “Responsive left-aligned hero with image“ on https://getbootstrap.com/docs/5.0/examples/heroes

**Comment by philippschmitt** [comment]
Suggested design for reference: 
![image](https://user-images.githubusercontent.com/940395/225745921-90c9eb00-d9b8-455e-bcdf-1835b41a700e.png)

Note that the previous OpenDataPhilly showed not just an image. The image also linked to a external website and showed image credits on hover. I thought we might not need to go all the way (though it would be nice) and could just include a static image, and uncredited. However, that requires having access to an image that looks good and is licensed appropriately. If that's even harder, I suggest replicating what's currently on OpenDataPhilly.
