### ISSUE TITLE
Shutdown CKAN

### ISSUE THREAD

**Issue by BryanQuigley** [azavea/opendataphilly-jkan#25]

**Comment by ran-codes** [comment]
Just curious why shift from CKAN to JKAN?

**Comment by BryanQuigley** [comment]
Cost and security. 

Also, this makes it easier for anyone to make a contribution to make other parts better - like copy text or themes, fix typos, etc.

Still working on streamlining a bunch of things though.  Suggestions (or PRs) welcome!
