### ISSUE TITLE
Markdown links not appearing correctly

### ISSUE THREAD

**Issue by lydiascarf** [azavea/opendataphilly-jkan#28]
Markdown links like those seen [here](https://next.opendataphilly.org/datasets/2009-2012-police-advisory-commission-complaints/) are not rendering correctly as inline links.

**Comment by BryanQuigley** [comment]
Figured out at least a workaround...

**Comment by BryanQuigley** [comment]
Outstanding question -
 Should we only allow organization level other links? (Not allow dataset specific other links as the mostly reference datasets we provide..)
