### ISSUE TITLE
Revise home page design

### ISSUE THREAD

**Issue by BryanQuigley** [azavea/opendataphilly-jkan#35]
Also doesn't need to mention JKAN on homepage.  

The icons might be easy to fix, I think it's just a sizing and color thing - they would look better if they were sized more proportionally to other page elements and had a color matching the theme.

**Comment by rcheetham** [comment]
- [ ] Revise color scheme
- [ ] integrate OpenDataPhilly logo
- [ ] revise icons
- [ ] revise text

Current OpenDataPhilly landing page text is:

Your source for open data in the Philadelphia region
OpenDataPhilly is a catalog of open data in the Philadelphia region. In addition to being the official open data repository for the City, it includes data sets from many organizations in the region.

**Comment by rcheetham** [comment]
potential text revision:

Welcome to OpenDataPhilly!
OpenDataPhilly is a catalog of open data in the Philadelphia region. In addition to being the official open data repository for the City of Philadelphia, it includes data sets from many organizations in the region.

**Comment by rcheetham** [comment]
Here's a screenshot of the previous design:

![image](https://github.com/azavea/opendataphilly-jkan/assets/595431/3e3c67ae-a88d-4b20-bcbd-506da02261a0)

Some additional screenshots of the previous version in these [GSlides](https://docs.google.com/presentation/d/1bUd9Wq1XpprGnaCEtdQrZ5KP3LmRvNGvjVhCYSvk1WE/edit#slide=id.g87185e79ab_0_606)
