### ISSUE TITLE
Markdown still broken in some places

### ISSUE THREAD

**Issue by BryanQuigley** [azavea/opendataphilly-jkan#36]
https://next.opendataphilly.org/datasets/311-service-and-information-requests/
for example

**Comment by rcheetham** [comment]
Example organization page: https://next.opendataphilly.org/organizations/city-of-philadelphia/

![image](https://user-images.githubusercontent.com/595431/230464305-aa4eef95-1a38-49ba-bf84-b5481c4b68bb.png)
