### ISSUE TITLE
"Open in GitHub" link generates 404 error

### ISSUE THREAD

**Issue by rcheetham** [azavea/opendataphilly-jkan#37]
There is a "Open in GitHub" link on the bottom of the left-side gutter. Clicking on it generates a GitHub 404 error. This link appears on each Organization and Dataset page. The link structure is:

 * Datasets - https://github.com/azavea/opendataphilly-jkan/edit/v2/_datasets/act-test-scores.md
 * Organizations - https://github.com/azavea/opendataphilly-jkan/edit/v2/_organizations/pa-department-of-education.md

![image](https://user-images.githubusercontent.com/595431/230463790-47bbf03b-f9cb-4394-9a0d-ad759448d337.png)

**Comment by BryanQuigley** [comment]
Fixed
