### ISSUE TITLE
Missing L&I Permits Building and Zoning Permits dataset?

### ISSUE THREAD

**Issue by Kistine** [azavea/opendataphilly-jkan#62]
I'm concerned we're missing a dataset, and wonder if it's due to a recent [pull request](https://github.com/azavea/opendataphilly-jkan/pull/58/files). However, it's also possible that the constricted search just means I'm having trouble finding it. I'm looking for L&I's Building and Zoning Permits dataset - it used to be filed under https://www.opendataphilly.org/dataset/licenses-and-inspections-building-permits

We recently updated it to include 'permit contractors' to help it show up in searches. When I searched 'building,' 'permits,' and 'zoning' or 'contractors,' I'm not finding it. Let me know if I'm just overlooking it in the search results.

**Comment by BryanQuigley** [comment]
It did break and is no longer on the site.  Their is some issue on the edit that I will need more time to understand. The GitHub checks ignored the error, but we should definitely change it so it reports something is wrong.

**Comment by rcheetham** [comment]
Confirming that the MD file is still there at https://github.com/azavea/opendataphilly-jkan/blob/main/_datasets/licenses-and-inspections-building-and-zoning-permits.md and there is a YAML error being thrown. 

![image](https://github.com/azavea/opendataphilly-jkan/assets/595431/d3ed46e8-2932-434e-8a9f-cdfb24484fbe)

**Comment by BryanQuigley** [comment]
It was just a spacing issue where the - description didn't line up with the rest of the doc anymore.

Also in PR #63 I added the option so Jekyll builds will fail if any of the markdown isn't correct.  This should prevent the builds from passing so this kind of thing wouldn't happen again.
