### ISSUE TITLE
Create a plan to enable us to track upstream easily

### ISSUE THREAD

**Issue by BryanQuigley** [azavea/opendataphilly-jkan#7]
We want to be able to track upstream easily and have other contributors to ODP here.  What needs to be considered to make it so we have very little chance of merge conflicts between us and upstream.

Should also include branch names etc.  Maybe we should have our changes in a separate branch?

**Comment by nlagrone** [comment]
Add documentation to repo

**Comment by BryanQuigley** [comment]
This problem is annoying: https://github.com/community/community/discussions/11729

May have to consider detaching - or just make good PR docs asking people to correct the automation

**Comment by BryanQuigley** [comment]
Requested to be detached from the jkan source, so we can just do it manually using git.
